# on workflow dispatch event
name: Build and Deploy
on:
  workflow_dispatch:

# then run build the next app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.109.123.250
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/admin/app"
      
      - name: Execute deployment script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 3.109.123.250
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              cd /home/admin/app
              npm install
              npm run build
              pm2 delete nextjs-app || true
              pm2 start npm --name nextjs-app -- run start -- -p 3000